### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by albertoHdzE** [remigenet/TKAT#1]
Hi!
I found super super interesting your job. I read your paper. Still wanting to replicate to understand how your implementation works.
I tried to run the example.ipynb, but dataset is missing
Is possible to be provided?
I was capable to make my own dataset downloading the hourly data from your list of assets from binance, but I still wondering if is possible to get access to your original dataset.

Addtionally, I was able to run your example with my dataset, but I wonder if it can be trained in my mac M2, or do I need GPU for using and training?
(
CORRECTION: Yes it was possible to run it in my M2. it took 17 min
<img width="325" alt="image" src="https://github.com/remigenet/TKAT/assets/8495777/18095c0c-1ce0-441f-971a-7e3249044663">

)

Thank you so much for any comment
And again, CONGRATULATIONS for your super amazing work

Best

**Comment by remigenet** [comment]
Hi,
Thanks a lot for your interests !
I just added a link to the dataset in the README of the examples part, which is in fact in the TKAN repository 

About the GPU yeah there is no reason it would be required, the code only relies on keras/tensorflow API which works for both, only difference will of course be performance ! I always had the opposite case, where code is not gpu compatible and only can run on cpu, but I never run tensorflow on mac so maybe it can happens ! Releasing soon a beta version of tkan that will maybe improve a bit the performance ! 

Best
